### ISSUE TITLE
Tests fail with ruff >0.0.265

### ISSUE THREAD

**Issue by polyzen** [charliermarsh/ruff-lsp#107]
```
FF
======================================================================
FAIL: test_linting_example (tests.test_server.TestServer.test_linting_example)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/ruff-lsp/src/ruff_lsp-0.0.26/tests/test_server.py", line 98, in test_linting_example
    self.assertEqual(actual, expected)
AssertionError: {'uri[132 chars]}}, 'message': '`sys` imported but unused', 's[477 chars]3}}]} != {'uri[132 chars]}}, 'data': {'fix': {'message': 'Remove unused[445 chars]f'}]}
  {'diagnostics': [{'code': 'F401',
+                   'data': {'fix': {'edits': [{'content': '',
-                   'data': {'fix': {'applicability': 'Unspecified',
-                                    'edits': [{'content': '',
                                                'end_location': {'column': 0,
                                                                 'row': 2},
                                                'location': {'column': 0,
                                                             'row': 1}}],
                                     'message': 'Remove unused import: `sys`'},
                             'noqa_row': 1},
                    'message': '`sys` imported but unused',
                    'range': {'end': {'character': 10, 'line': 0},
                              'start': {'character': 7, 'line': 0}},
                    'severity': 2,
                    'source': 'Ruff',
                    'tags': [1]},
                   {'code': 'F821',
                    'data': {'fix': None, 'noqa_row': 3},
                    'message': 'Undefined name `x`',
                    'range': {'end': {'character': 7, 'line': 2},
                              'start': {'character': 6, 'line': 2}},
                    'severity': 1,
                    'source': 'Ruff'}],
   'uri': 'file:///tmp/tmpjz3mhkpm.py'}

======================================================================
FAIL: test_no_initialization_options (tests.test_server.TestServer.test_no_initialization_options)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/ruff-lsp/src/ruff_lsp-0.0.26/tests/test_server.py", line 181, in test_no_initialization_options
    self.assertEqual(actual, expected)
AssertionError: {'uri[132 chars]}}, 'message': '`sys` imported but unused', 's[477 chars]3}}]} != {'uri[132 chars]}}, 'data': {'fix': {'message': 'Remove unused[445 chars]f'}]}
  {'diagnostics': [{'code': 'F401',
+                   'data': {'fix': {'edits': [{'content': '',
-                   'data': {'fix': {'applicability': 'Unspecified',
-                                    'edits': [{'content': '',
                                                'end_location': {'column': 0,
                                                                 'row': 2},
                                                'location': {'column': 0,
                                                             'row': 1}}],
                                     'message': 'Remove unused import: `sys`'},
                             'noqa_row': 1},
                    'message': '`sys` imported but unused',
                    'range': {'end': {'character': 10, 'line': 0},
                              'start': {'character': 7, 'line': 0}},
                    'severity': 2,
                    'source': 'Ruff',
                    'tags': [1]},
                   {'code': 'F821',
                    'data': {'fix': None, 'noqa_row': 3},
                    'message': 'Undefined name `x`',
                    'range': {'end': {'character': 7, 'line': 2},
                              'start': {'character': 6, 'line': 2}},
                    'severity': 1,
                    'source': 'Ruff'}],
   'uri': 'file:///tmp/tmpvu2p4_pc.py'}

----------------------------------------------------------------------
Ran 2 tests in 0.854s

FAILED (failures=2)
```

**Comment by charliermarsh** [comment]
The tests require Ruff v0.0.266 which I just yanked. I'll update to v0.0.267 in a few minutes.

**Comment by charliermarsh** [comment]
Ok, should be working on main.

**Comment by polyzen** [comment]
Works, thank you.
