### ISSUE TITLE
 `textDocument/codeAction` crashes when there are no actions

### ISSUE THREAD

**Issue by WhyNotHugo** [charliermarsh/ruff-lsp#55]
Trying to enumerate actions for a line crashes if there are no available actions for the current position.

On neovim, I get the errors:

```
LSP[ruff_lsp] Unexpected error in LSP server, see server's logs for details                                                   
[Fzf-lua] Error executing 'textDocument/codeAction': timeout                                                                  
```

The LSP logs neovim generates are, regrettably, not the easiest to read:

```
[ERROR][2023-01-17 16:08:01] .../vim/lsp/rpc.lua:733	"rpc"	"ruff-lsp"	"stderr"	"Unable to deserialize message\n  + Exception Group Traceback (most recent call last):\n  |   File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 401, in _deserialize_message\n  |     return self._converter.structure(data, request_type)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/usr/lib/python3.11/site-packages/cattrs/converters.py\", line 309, in structure\n  |     return self._structure_func.dispatch(cl)(obj, cl)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>\", line 26, in structure_TextDocumentCodeActionRequest\n  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)\n  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Exception Group Traceback (most recent call last):\n    |   File \"<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>\", line 10, in structure_TextDocumentCodeActionRequest\n    |     res['params'] = __c_structure_params(o['params'], __c_type_params)\n    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"<cattrs generated structure lsprotocol.types.CodeActionParams>\", line 31, in structure_CodeActionParams\n    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)\n    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (1 sub-exception)\n    | Structuring class TextDocumentCodeActionRequest @ attribute params\n    +-+---------------- 1 ----------------\n      | Exception Group Traceback (most recent call last):\n      |   File \"<cattrs generated structure lsprotocol.types.CodeActionParams>\", line 15, in structure_CodeActionParams\n      |     res['context'] = __c_structure_context(o['context'], __c_type_context)\n      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      |   File \"<cattrs generated structure lsprotocol.types.CodeActionContext>\", line 21, in structure_CodeActionContext\n      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)\n      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)\n      | Structuring class CodeActionParams @ attribute context\n      +-+---------------- 1 ----------------\n        | Traceback (most recent call last):\n        |   File \"<cattrs generated structure lsprotocol.types.CodeActionContext>\", line 5, in structure_CodeActionContext\n        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)\n        |                                                     ~^^^^^^^^^^^^^^^\n        | TypeError: list indices must be integers or slices, not str\n        | Structuring class CodeActionContext @ attribute diagnostics\n        +------------------------------------\n\n"
[ERROR][2023-01-17 16:08:01] .../vim/lsp/rpc.lua:733	"rpc"	"ruff-lsp"	"stderr"	"Error receiving data\n  + Exception Group Traceback (most recent call last):\n  |   File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 401, in _deserialize_message\n  |     return self._converter.structure(data, request_type)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"/usr/lib/python3.11/site-packages/cattrs/converters.py\", line 309, in structure\n  |     return self._structure_func.dispatch(cl)(obj, cl)\n  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>\", line 26, in structure_TextDocumentCodeActionRequest\n  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)\n  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Exception Group Traceback (most recent call last):\n    |   File \"<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>\", line 10, in structure_TextDocumentCodeActionRequest\n    |     res['params'] = __c_structure_params(o['params'], __c_type_params)\n    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"<cattrs generated structure lsprotocol.types.CodeActionParams>\", line 31, in structure_CodeActionParams\n    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)\n    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (1 sub-exception)\n    | Structuring class TextDocumentCodeActionRequest @ attribute params\n    +-+---------------- 1 ----------------\n      | Exception Group Traceback (most recent call last):\n      |   File \"<cattrs generated structure lsprotocol.types.CodeActionParams>\", line 15, in structure_CodeActionParams\n      |     res['context'] = __c_structure_context(o['context'], __c_type_context)\n      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      |   File \"<cattrs generated structure lsprotocol.types.CodeActionContext>\", line 21, in structure_CodeActionContext\n      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)\n      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)\n      | Structuring class CodeActionParams @ attribute context\n      +-+---------------- 1 ----------------\n        | Traceback (most recent call last):\n        |   File \"<cattrs generated structure lsprotocol.types.CodeActionContext>\", line 5, in structure_CodeActionContext\n        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)\n        |                                                     ~^^^^^^^^^^^^^^^\n        | TypeError: list indices must be integers or slices, not str\n        | Structuring class CodeActionContext @ attribute diagnostics\n        +------------------------------------\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 507, in data_received\n    self._data_received(data)\n  File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 539, in _data_received\n    json.loads(body.decode(self.CHARSET),\n  File \"/usr/lib/python3.11/json/__init__.py\", line 359, in loads\n    return cls(**kw).decode(s)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\n               ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/site-packages/pygls/protocol.py\", line 415, in _deserialize_message\n    raise JsonRpcInvalidParams() from exc\npygls.exceptions.JsonRpcInvalidParams: Invalid Params\n"
[ERROR][2023-01-17 16:08:06] .../vim/lsp/rpc.lua:733	"rpc"	"pylsp"	"stderr"	"2023-01-17 16:08:06,200 CET - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 2\n"
[ERROR][2023-01-17 16:08:06] .../vim/lsp/rpc.lua:733	"rpc"	"ruff-lsp"	"stderr"	'Cancel notification for unknown message id "2"\n'
```

I managed to unmangle it a bit tho. The big string in the first error is:

```
 "Unable to deserialize message
  + Exception Group Traceback (most recent call last):
  |   File "/usr/lib/python3.11/site-packages/pygls/protocol.py", line 401, in _deserialize_message
  |     return self._converter.structure(data, request_type)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/site-packages/cattrs/converters.py", line 309, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 26, in structure_TextDocumentCodeActionRequest
  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 10, in structure_TextDocumentCodeActionRequest
    |     res['params'] = __c_structure_params(o['params'], __c_type_params)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 31, in structure_CodeActionParams
    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (1 sub-exception)
    | Structuring class TextDocumentCodeActionRequest @ attribute params
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 15, in structure_CodeActionParams
      |     res['context'] = __c_structure_context(o['context'], __c_type_context)
      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 21, in structure_CodeActionContext
      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)
      | Structuring class CodeActionParams @ attribute context
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 5, in structure_CodeActionContext
        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)
        |                                                     ~^^^^^^^^^^^^^^^
        | TypeError: list indices must be integers or slices, not str
        | Structuring class CodeActionContext @ attribute diagnostics
        +------------------------------------
```

And the other one is:

```
 "Error receiving data
  + Exception Group Traceback (most recent call last):
  |   File "/usr/lib/python3.11/site-packages/pygls/protocol.py", line 401, in _deserialize_message
  |     return self._converter.structure(data, request_type)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/site-packages/cattrs/converters.py", line 309, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 26, in structure_TextDocumentCodeActionRequest
  |     if errors: raise __c_cve('While structuring ' + 'TextDocumentCodeActionRequest', errors, __cl)
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | cattrs.errors.ClassValidationError: While structuring TextDocumentCodeActionRequest (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure lsprotocol.types.TextDocumentCodeActionRequest>", line 10, in structure_TextDocumentCodeActionRequest
    |     res['params'] = __c_structure_params(o['params'], __c_type_params)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 31, in structure_CodeActionParams
    |     if errors: raise __c_cve('While structuring ' + 'CodeActionParams', errors, __cl)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | cattrs.errors.ClassValidationError: While structuring CodeActionParams (1 sub-exception)
    | Structuring class TextDocumentCodeActionRequest @ attribute params
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure lsprotocol.types.CodeActionParams>", line 15, in structure_CodeActionParams
      |     res['context'] = __c_structure_context(o['context'], __c_type_context)
      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 21, in structure_CodeActionContext
      |     if errors: raise __c_cve('While structuring ' + 'CodeActionContext', errors, __cl)
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | cattrs.errors.ClassValidationError: While structuring CodeActionContext (1 sub-exception)
      | Structuring class CodeActionParams @ attribute context
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "<cattrs generated structure lsprotocol.types.CodeActionContext>", line 5, in structure_CodeActionContext
        |     res['diagnostics'] = __c_structure_diagnostics(o['diagnostics'], __c_type_diagnostics)
        |                                                     ~^^^^^^^^^^^^^^^
        | TypeError: list indices must be integers or slices, not str
        | Structuring class CodeActionContext @ attribute diagnostics
        +------------------------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pygls/protocol.py", line 507, in data_received
    self._data_received(data)
  File "/usr/lib/python3.11/site-packages/pygls/protocol.py", line 539, in _data_received
    json.loads(body.decode(self.CHARSET),
  File "/usr/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pygls/protocol.py", line 415, in _deserialize_message
    raise JsonRpcInvalidParams() from exc
pygls.exceptions.JsonRpcInvalidParams: Invalid Params
```

The file/code being edited seems to be irrelevant. I can repro with the following minimal file:

```py
print(1)
```

**Comment by WhyNotHugo** [comment]
I can also reproduce this by trying to use code actions on a line with no code actions even if there are actions on another line.

**Comment by WhyNotHugo** [comment]
I'm using nvim-lspconfig for configuring the LSP and fzf-lua to trigger code actions.

**Comment by charliermarsh** [comment]
Will try this out tonight -- sorry for delay.

**Comment by charliermarsh** [comment]
I'm having trouble reproducing this. I'm guessing it has something to do with Fzf-lua which I've never used :(

![Screen Shot 2023-01-18 at 7 36 45 PM](https://user-images.githubusercontent.com/1309177/213328332-ad3a1fde-02f0-49e6-8ab8-21d3be3d8419.png)

**Comment by WhyNotHugo** [comment]
I've [reported this on the fzf-lua side](https://github.com/ibhagwan/fzf-lua/issues/707), since the issue is specifically when using it. I'm not sure if it does anything different when generating the requests.
