### ISSUE TITLE
ruff-lsp errors out in nvim

### ISSUE THREAD

**Issue by balsa-sarenac** [charliermarsh/ruff-lsp#63]
I'm trying to setup `ruff-lsp` with neovim. When opening a python file in nvim I get the following message:
`Client 2 quit with exit code 1 and signal 0`

LspLogs:
```
[START][2023-01-30 17:08:29] LSP logging initiated
[ERROR][2023-01-30 17:08:29] .../vim/lsp/rpc.lua:734	"rpc"	"ruff-lsp"	"stderr"
'Traceback (most recent call last):
  File "/Users/balsa/.pyenv/versions/3.10.8/bin/ruff-lsp", line 8, in <module'
[ERROR][2023-01-30 17:08:29] .../vim/lsp/rpc.lua:734	"rpc"	"ruff-lsp"	"stderr"	
"    sys.exit(main())
File "/Users/balsa/.pyenv/versions/3.10.8/lib/python3.10/site-packages/ruff_lsp/__main__.py", line 5, in main
        from ruff_lsp import __version__, server
File "/Users/balsa/.pyenv/versions/3.10.8/lib/python3.10/site-packages/ruff_lsp/server.py", line 51, in <module>
        from pygls import protocol, server, uris, workspace
File "/Users/balsa/.pyenv/versions/3.10.8/lib/python3.10/site-packages/pygls/protocol.py", line 33, in <module>
        from cattrs.errors import ClassValidationError\nImportError: cannot import name 'ClassValidationError' from 'cattrs.errors'
(/Users/balsa/.pyenv/versions/3.10.8/lib/python3.10/site-packages/cattrs/errors.py)"
```

Versions of all related packages:
```
ruff                       0.0.237
ruff-lsp                   0.0.16
cattrs                     1.10.0
pygls                      1.0.0
```

Another possible cause is my `neovim` config. I used `lsp-zero` to configure the LSP. Here is the `ruff-lsp` setup code:
```
require'lspconfig'.ruff_lsp.setup{
  init_options = {
    settings = {
      args = { },
    }
  }
}
```

I've reached out to @tombh to check if this is something `pygls`, and he suggested to open an issue here to kick off the discussion.

**Comment by charliermarsh** [comment]
Interesting... Can you try upgrading `cattrs`? The VS Code extension pins it at `22.2.0`:

```
cattrs==22.2.0 \
    --hash=sha256:bc12b1f0d000b9f9bee83335887d532a1d3e99a833d1bf0882151c97d3e68c21 \
    --hash=sha256:f0eed5642399423cf656e7b66ce92cdc5b963ecafd041d1b24d136fdde7acf6d
    # via lsprotocol
```

**Comment by balsa-sarenac** [comment]
That fixed it! Thanks for the help and quick reply!

**Comment by charliermarsh** [comment]
Oh awesome! No problem!
